up the version number to come in line for GitHub tags
nanograv/enterprise_extensions pull request #124
Opened 2021-08-06 22:12 UTC by Hazboun6

This PR simply increases the version number to v2.1.0. This brings the package version numbers in line with the tagged versions of the code on GitHub. Once this is merged we can then Tag this version so there is an archive of the version of enterprise extensions _with_ the outlier code. This is what the timing working group has been using for their current analyses, so it it seems prudent to make this tagged version. The `tar` file is ready to go for the tagging, once this PR is accepted.

2021-08-06 23:31 UTC, paulthebaker requested changes
Can you also up the version number in the citation recommendation in `README.md`?

2021-08-06 23:31 UTC, paulthebaker commented
Oh wow!  I didn't realize there were already tagged versions 1.0 and 2.0

2021-08-06 23:33 UTC, Hazboun6 commented
> Oh wow! I didn't realize there were already tagged versions 1.0 and 2.0

Yeah, that's why there is the big jump in the package version number...

2021-08-07 14:48 UTC, paulthebaker approved these changes

2021-08-09 17:07 UTC, merged