Cover more priors with empirical distribution extension function
nanograv/enterprise_extensions pull request #180
Opened 2022-04-28 18:37 UTC by AaronDJohnson

This adds support for Normal and Uniform priors to be covered automatically by empirical distributions. Additionally, I have added a skip if the empirical distribution is outside of these functions with a warning that asks the user to make sure they are covering their priors.

Priors with a size attribute should also be covered here (e.g. free spectral red noise models).

2022-04-28 18:39 UTC, AaronDJohnson commented
Hopefully fixing #179

2022-04-28 20:08 UTC, Hazboun6 requested changes
We need to fix the handling of array-sampled parameters, specifically if there are single-sampled parameters later in the `param` list.

2022-04-28 20:18 UTC, Hazboun6 commented
Also, this PR probably needs a unit test. They could be tacked onto the other empirical distribution tests.

2022-05-12 02:01 UTC, closed without merging

2022-05-12 02:17 UTC, AaronDJohnson commented
Oops! I thought it was merged already. I'll undo the delete and reopen the PR 👍