Dcbusyweek
nanograv/enterprise_extensions pull request #231
Opened 2024-04-15 07:13 UTC by vhaasteren

Merging busy-week updates (mostly Fe statistic corrections)

2025-03-05 15:14 UTC, vhaasteren commented
@achalumeau , it seems like we are getting closer to getting this merged. We probably just need to merge #248 to get it in

2025-03-12 15:58 UTC, vhaasteren commented
It took me a while to get this PR ready. There were still missing imports, functions moved around, and everything. But in the end I got it in good shape. The OS code is improved: the original code had bugs, so the changes of keyword arguments is a good thing here. I am of the opinion this can all be merged.


## Breaking Changes

### 1. `dropout_powerlaw` (in `enterprise_extensions/dropout.py`)
- **Old signature:**  
  ```python
  dropout_powerlaw(f, name, log10_A=-16, gamma=5, dropout_psr='B1855+09', k_drop=0.5, k_threshold=0.5)
  ```
- **New signature:**  
  ```python
  dropout_powerlaw(
      f,
      name,
      log10_A=-16,
      gamma=5,
      dropout_psr="all",
      k_drop=None,
      dropbin_psr="all",
      k_dropbin=None,
      k_threshold=0.5,
  )
  ```
- **Breaking changes:**  
  - The keyword `dropout_psr` now defaults to `"all"` instead of `'B1855+09'`.
  - The keyword `k_drop` now defaults to `None` instead of `0.5`.
  - Two new keyword arguments (`dropbin_psr` and `k_dropbin`) have been added.

---

### 2. `innerProduct_rr` (used in frequentist routines such as F‑statistic/Fe‑statistic)
- **Old signature:**  
  ```python
  innerProduct_rr(x, y, Nmat, Tmat, Sigma, TNx=None, TNy=None, brave=False)
  ```
- **New signature:**  
  ```python
  innerProduct_rr(x, y, Nvec, Tmat, TNT, Sigma, brave=False)
  ```
- **Breaking changes:**  
  - The parameters `Nmat`, `TNx`, and `TNy` have been replaced by **required** arguments `Nvec` and `TNT`.  
  - Code calling this function must now provide these objects in the new order.
  
  Note that the original innerProduct_rr was absolutely incorrect, as it did things like `1/Nvec`, whereas `Nvec.solve` should ALWAYS be used.

---

### 3. Kernel Functions (e.g. `get_tf_quantization_matrix`)
- **Change:**  
  - A new keyword argument `dm_idx` (defaulting to `2`) has been added.
- **Impact:**  
  - If you relied on positional arguments for frequency‐dependent scaling, ensure that the new parameter ordering does not shift your intended values.

---

## Default Keyword Changes

- **`dropout_powerlaw`:**
  - `dropout_psr`: Default changed from `'B1855+09'` to `"all"`.
  - `k_drop`: Default changed from `0.5` to `None`.

- **`innerProduct_rr`:**
  - The old optional parameters (`TNx` and `TNy`) are no longer present; they have been replaced by required parameters (`Nvec` and `TNT`). There is no default for these anymore. Note that the original code was incorrect

- **Kernel routines:**
  - The new keyword `dm_idx` in `get_tf_quantization_matrix` now defaults to `2`.

2025-04-02 19:34 UTC, AaronDJohnson requested changes
We need to increase the major version number with this merge so that we can perform a new release.

I didn't catch anything wrong here.

In the future **do not** do linting alongside other changes. It makes the changes very difficult to parse. On top of that, I had to look more carefully at several thousand lines. It diminishes the quality of the review.

Add the version bump and let's get this merged so we can do a new release.

2025-04-03 11:07 UTC, vhaasteren commented on enterprise_extensions/frequentist/Fe_statistic.py
> +Feb 2019, Bence Becsy (NANOGrav):   created file, implemented FeStatistics
You are right. I'm removing it

2025-04-03 11:12 UTC, vhaasteren commented on enterprise_extensions/hypermodel.py
> +        if any([str(p).split(":")[0] for p in list(self.params) if "gw" in str(p)]):
Changed back

2025-04-03 11:15 UTC, vhaasteren commented on enterprise_extensions/model_orfs.py
> +    Author: S. Chen (2023)
Yeah, I agree with you, but these ones I will leave in. It's all over the place in this file, from before this PR also.

2025-04-03 11:29 UTC, vhaasteren commented on enterprise_extensions/hypermodel.py
> +        self.snames = dict.fromkeys(
Often when the linter does a bad job it's actually a sign that the line of code should probably be broken up.

But changing it back won't make the CI trip, so I'm happy with that

2025-04-03 16:10 UTC, AaronDJohnson approved these changes

2025-04-03 16:10 UTC, merged